#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param command ss-redir -c /etc/shadowsocks/shadowsocks.json -v > /tmp/ss-redir.log
    procd_close_instance
}
